export const locale = {
    "locale": "zh-CN",
    "strings": {
        "newFormHeader": "预约",
        "editFormHeader": "编辑预约",
        "newRecurrenceFormHeader": "周期",
        "editRecurrenceFormHeader": "编辑周期",
        "cueFormHeader": "产品提示",
        "dateCaption": "日期",
        "datesCaption": "日期",
        "subjectCaption": "主题",
        "startTimeCaption": "开始时间",
        "endTimeCaption": "结束时间",
        "allDayEventCaption": "全天项目",
        "reminderCaption": "提醒",
        "detailsCaption": "详情",
        "contactsCaption": "联系人",
        "todayCaption": "今天",
        "locationCaption": "位置",
        "patternCaption": "模式",
        "rangeCaption": "周期范围",
        "everyCaption": "每",
        "ofEveryCaption": "每个",
        "startCaption": "开始",
        "noEndCaption": "无结束日期",
        "endAfterCaption": "发生次数",
        "endDateCaption": "截止日期",
        "saveButtonCaption": "保存",
        "optionsButtonCaption": "选项",
        "cancelButtonCaption": "取消",
        "recurrenceButtonCaption": "周期",
        "deleteButtonCaption": "删除",
        "secondsValue": "秒",
        "minuteValue": "分钟",
        "minutesValue": "分钟",
        "hourValue": "小时",
        "hoursValue": "小时",
        "dayValue": "天",
        "daysValue": "天",
        "weeksValue": "周",
        "monthValue": "月",
        "dailyValue": "每日",
        "weeklyValue": "每周",
        "monthlyValue": "每月",
        "yearlyValue": "每年",
        "intervalValue": "按时间间隔",
        "firstValue": "第一个",
        "secondValue": "第二个",
        "thirdValue": "第三个",
        "fourthValue": "第四个",
        "lastValue": "最后一个",
        "weekendValue": "周末",
        "weekdayValue": "工作日",
        "recurrenceDailyOnePattern": "每天发生",
        "recurrenceDailyTwoPattern": "每 [Days] 天发生",
        "recurrenceDailyThreePattern": "每周发生",
        "recurrenceDailyFourPattern": "每工作日发生",
        "recurrenceWeeklyOnePattern": "每 [DaysOfWeek]发生",
        "recurrenceWeeklyTwoPattern": "每 [Weeks] 周发生在 [DaysOfWeek]天",
        "recurrenceMonthlyOnePattern": "每[Months]月的 [DayOfMonth] 天发生",
        "recurrenceMonthlyTwoPattern": "每[Months]的[Occurrence] [Day] 天发生",
        "recurrenceYearlyOnePattern": "每[MonthOfYear]月 [DayOfMonth]天发生",
        "recurrenceYearlyTwoPattern": "每[MonthOfYear]月 [Occurrence] [Day] 天发生",
        "recurrenceIntervalPattern": "每 [Interval.Days] 天[Interval.Hours] 小时 [Interval.Minutes] 分钟 [Interval.Seconds] 秒发生",
        "recurrenceStartDatePattern": "[StartDate]生效",
        "recurrenceEndDatePattern": "直到 [EndDate]",
        "recurrenceTimeOnePattern": "从[StartTime]到[EndTime]",
        "recurrenceTimeTwoPattern": "在[StartTime]",
        "taskFormHeader": "任务",
        "taskPriorityLow": "低",
        "taskPriorityNormal": "正常",
        "taskPriorityHigh": "高",
        "taskStatusNotStarted": "未开始",
        "taskStatusInProgress": "进行中",
        "taskStatusCompleted": "已完成",
        "taskStatusWaiting": "等待他人",
        "taskStatusDeferred": "延期",
        "percentCompleteCaption": "% 完成",
        "dueDateCaption": "截止日期",
        "priorityCaption": "优先级",
        "startDateCaption": "开始日期",
        "statusCaption": "状态",
        "timeCaption": "时间",
        "oKButtonCaption": "确定",
        "removeButtonCaption": "移除",
        "weekValue": "周",
        "durationCaption": "时段",
        "endCaption": "结束",
        "daysCaption": "天",
        "hoursCaption": "小时",
        "minutesCaption": "分钟",
        "secondsCaption": "秒",
        "monthsValue": "月",
        "recurEveryValue": "每隔",
        "occurrencesValue": "次出现",
        "weeksOnValue": "在星期",
        "everyWeekdayValue": "每个工作日",
        "everyWeekendValue": "每个周末",
        "theValue": "那",
        "invalidRecurrenceIntervalHeader": "无效周期",
        "invalidRecurrenceIntervalMessage": "周期间隔应大于零.",
        "confirmRecurrenceRemoveHeader": "移除周期",
        "confirmRecurrenceRemoveMessage": "确认移除周期？"
    }
};