export const locale = {
    "locale": "it-IT",
    "strings": {
        "newFormHeader": "Appuntamento",
        "editFormHeader": "Modifica Appuntamento",
        "newRecurrenceFormHeader": "Ricorrenza",
        "editRecurrenceFormHeader": "Modifica Ricorrenza",
        "cueFormHeader": "Elementi promemoria",
        "dateCaption": "Data",
        "datesCaption": "Date",
        "subjectCaption": "Oggetto",
        "startTimeCaption": "Ora inizio",
        "endTimeCaption": "Ora fine",
        "allDayEventCaption": "Evento tutto il giorno",
        "reminderCaption": "Promemoria",
        "detailsCaption": "Dettagli",
        "contactsCaption": "Contatti",
        "todayCaption": "Oggi",
        "locationCaption": "Posizione",
        "patternCaption": "Modello",
        "rangeCaption": "Intervallo di ricorrenza",
        "everyCaption": "Ogni",
        "ofEveryCaption": "di ogni",
        "startCaption": "Inizio",
        "noEndCaption": "Nessuna data di fine",
        "endAfterCaption": "Fine dopo",
        "endDateCaption": "Fine entro",
        "saveButtonCaption": "Salva",
        "optionsButtonCaption": "Opzioni",
        "cancelButtonCaption": "Annulla",
        "recurrenceButtonCaption": "Ricorrenza",
        "deleteButtonCaption": "Elimina",
        "secondsValue": "secondi",
        "minuteValue": "minuto",
        "minutesValue": "minuti",
        "hourValue": "ora",
        "hoursValue": "ore",
        "dayValue": "giorno",
        "daysValue": "giorni",
        "weeksValue": "settimane",
        "monthValue": "mese",
        "dailyValue": "Giornaliero",
        "weeklyValue": "Settimanale",
        "monthlyValue": "Mensile",
        "yearlyValue": "Annuale",
        "intervalValue": "Per intervallo di tempo",
        "firstValue": "primo",
        "secondValue": "secondo",
        "thirdValue": "terzo",
        "fourthValue": "quarto",
        "lastValue": "ultimo",
        "weekendValue": "fine settimana",
        "weekdayValue": "giorno feriale",
        "recurrenceDailyOnePattern": "Si verifica ogni giorno",
        "recurrenceDailyTwoPattern": "Si verifica ogni [Days] giorni",
        "recurrenceDailyThreePattern": "Si verifica ogni giorno feriale",
        "recurrenceDailyFourPattern": "Si verifica ogni fine settimana",
        "recurrenceWeeklyOnePattern": "Si verifica ogni [DaysOfWeek]",
        "recurrenceWeeklyTwoPattern": "Si verifica ogni [Weeks] settimane il [DaysOfWeek]",
        "recurrenceMonthlyOnePattern": "Si verifica il giorno [DayOfMonth] ogni [Months] mese(i)",
        "recurrenceMonthlyTwoPattern": "Si verifica il [Occurrence] [Day] ogni [Months] mese(i)",
        "recurrenceYearlyOnePattern": "Si verifica ogni [MonthOfYear] [DayOfMonth]",
        "recurrenceYearlyTwoPattern": "Si verifica il [Occurrence] [Day] di [MonthOfYear]",
        "recurrenceIntervalPattern": "Si verifica ogni [Interval.Days] giorni [Interval.Hours] ore [Interval.Minutes] minuti [Interval.Seconds] secondi",
        "recurrenceStartDatePattern": "effettivo [StartDate]",
        "recurrenceEndDatePattern": "fino a [EndDate]",
        "recurrenceTimeOnePattern": "dalle [StartTime] alle [EndTime]",
        "recurrenceTimeTwoPattern": "alle [StartTime]",
        "taskFormHeader": "Attività",
        "taskPriorityLow": "Bassa",
        "taskPriorityNormal": "Normale",
        "taskPriorityHigh": "Alta",
        "taskStatusNotStarted": "Non iniziato",
        "taskStatusInProgress": "In corso",
        "taskStatusCompleted": "Completato",
        "taskStatusWaiting": "In attesa di qualcun altro",
        "taskStatusDeferred": "Rimandato",
        "percentCompleteCaption": "% Completato",
        "dueDateCaption": "Data di scadenza",
        "priorityCaption": "Priorità",
        "startDateCaption": "Data inizio",
        "statusCaption": "Stato",
        "timeCaption": "Ora",
        "oKButtonCaption": "OK",
        "removeButtonCaption": "Rimuovi",
        "weekValue": "settimana",
        "durationCaption": "Durata",
        "endCaption": "Fine",
        "daysCaption": "Giorni",
        "hoursCaption": "Ore",
        "minutesCaption": "Minuti",
        "secondsCaption": "Secondi",
        "monthsValue": "mese(i)",
        "recurEveryValue": "Ricorre ogni",
        "occurrencesValue": "occorrenze",
        "weeksOnValue": "settimana(e) il",
        "everyWeekdayValue": "Ogni giorno feriale",
        "everyWeekendValue": "Ogni giorno di fine settimana",
        "theValue": "Il",
        "invalidRecurrenceIntervalHeader": "Intervallo di ricorrenza non valido",
        "invalidRecurrenceIntervalMessage": "L'intervallo di ricorrenza deve essere maggiore di zero.",
        "confirmRecurrenceRemoveHeader": "Rimuovi ricorrenza",
        "confirmRecurrenceRemoveMessage": "Confermi la rimozione della ricorrenza?"
    }
};