export const locale = {
  "locale": "ko-KR",
  "strings": {
    "newFormHeader": "일정",
    "editFormHeader": "일정 편집",
    "newRecurrenceFormHeader": "반복",
    "editRecurrenceFormHeader": "반복 편집",
    "cueFormHeader": "신호 항목",
    "dateCaption": "날짜",
    "datesCaption": "날짜",
    "subjectCaption": "제목",
    "startTimeCaption": "시작 시간",
    "endTimeCaption": "종료 시간",
    "allDayEventCaption": "종일 이벤트",
    "reminderCaption": "알림",
    "detailsCaption": "세부 사항",
    "contactsCaption": "연락처",
    "todayCaption": "오늘",
    "locationCaption": "위치",
    "patternCaption": "패턴",
    "rangeCaption": "반복 범위",
    "everyCaption": "각",
    "ofEveryCaption": "각",
    "startCaption": "시작",
    "noEndCaption": "종료일 없음",
    "endAfterCaption": "종료 후",
    "endDateCaption": "종료 시간",
    "saveButtonCaption": "저장",
    "optionsButtonCaption": "옵션",
    "cancelButtonCaption": "취소",
    "recurrenceButtonCaption": "반복",
    "deleteButtonCaption": "삭제",
    "secondsValue": "초",
    "minuteValue": "분",
    "minutesValue": "분",
    "hourValue": "시간",
    "hoursValue": "시간",
    "dayValue": "일",
    "daysValue": "일",
    "weeksValue": "주",
    "monthValue": "월",
    "dailyValue": "일일",
    "weeklyValue": "매주",
    "monthlyValue": "매월",
    "yearlyValue": "매년",
    "intervalValue": "시간 간격",
    "firstValue": "첫 번째",
    "secondValue": "두 번째",
    "thirdValue": "세 번째",
    "fourthValue": "네 번째",
    "lastValue": "마지막",
    "weekendValue": "주말",
    "weekdayValue": "평일",
    "recurrenceDailyOnePattern": "매일 발생",
    "recurrenceDailyTwoPattern": "[Days] 일 마다 발생",
    "recurrenceDailyThreePattern": "매주 평일 발생",
    "recurrenceDailyFourPattern": "매주 주말 발생",
    "recurrenceWeeklyOnePattern": "[DaysOfWeek]마다 발생",
    "recurrenceWeeklyTwoPattern": "매 [Weeks] 주의 [DaysOfWeek]마다 발생",
    "recurrenceMonthlyOnePattern": "매 [Months] 월의 [DayOfMonth]에 발생",
    "recurrenceMonthlyTwoPattern": "매 [Months]에 [Occurrence] [Day] 발생",
    "recurrenceYearlyOnePattern": "[MonthOfYear] [DayOfMonth]에 발생",
    "recurrenceYearlyTwoPattern": "[MonthOfYear]의 [Occurrence] [Day]에 발생",
    "recurrenceIntervalPattern": "[Interval.Days] 일 [Interval.Hours] 시간 [Interval.Minutes] 분 [Interval.Seconds] 초 마다 발생",
    "recurrenceStartDatePattern": "[StartDate]에 유효",
    "recurrenceEndDatePattern": "[EndDate]까지",
    "recurrenceTimeOnePattern": "[StartTime]부터[EndTime]까지",
    "recurrenceTimeTwoPattern": "[StartTime]부터",
    "taskFormHeader": "작업",
    "taskPriorityLow": "낮음",
    "taskPriorityNormal": "일반",
    "taskPriorityHigh": "높음",
    "taskStatusNotStarted": "아직 시작되지 않음",
    "taskStatusInProgress": "진행 중",
    "taskStatusCompleted": "완료됨",
    "taskStatusWaiting": "다른 사람을 기다리는 중",
    "taskStatusDeferred": "연기됨",
    "percentCompleteCaption": "% 완료",
    "dueDateCaption": "마감 기한",
    "priorityCaption": "우선 사항",
    "startDateCaption": "시작일",
    "statusCaption": "상태",
    "timeCaption": "시간",
    "oKButtonCaption": "확인",
    "removeButtonCaption": "제거",
    "weekValue": "주",
    "durationCaption": "기간",
    "endCaption": "종료",
    "daysCaption": "일",
    "hoursCaption": "시",
    "minutesCaption": "분",
    "secondsCaption": "초",
    "monthsValue": "월",
    "recurEveryValue": "매일 반복",
    "occurrencesValue": "발생",
    "weeksOnValue": "주",
    "everyWeekdayValue": "평일마다",
    "everyWeekendValue": "주말마다",
    "theValue": "그",
    "invalidRecurrenceIntervalHeader": "잘못된 반복",
    "invalidRecurrenceIntervalMessage": "반복 간격은 0 보다 커야합니다.",
    "confirmRecurrenceRemoveHeader": "반복 제거",
    "confirmRecurrenceRemoveMessage": "반복 제거를 확인하시겠습니까?"
  }
};