export const locale = {
  "locale": "pl-PL",
  "strings": {
    "newFormHeader": "Spotkanie",
    "editFormHeader": "Edytuj spotkanie",
    "newRecurrenceFormHeader": "Powtarzalność",
    "editRecurrenceFormHeader": "Edytuj powtarzalność",
    "cueFormHeader": "Pozycje podpowiedzi",
    "dateCaption": "Data",
    "datesCaption": "Daty",
    "subjectCaption": "Przedmiot",
    "startTimeCaption": "Czas rozpoczęcia",
    "endTimeCaption": "Czas zakończenia",
    "allDayEventCaption": "Wszystkie zdarzenia dzienne",
    "reminderCaption": "Przypomnienie",
    "detailsCaption": "Szczegóły",
    "contactsCaption": "Kontakty",
    "todayCaption": "Dzisiaj",
    "locationCaption": "Lokalizacja",
    "patternCaption": "Wzór",
    "rangeCaption": "Zakres powtarzalności",
    "everyCaption": "Każdy",
    "ofEveryCaption": "każdego",
    "startCaption": "Start",
    "noEndCaption": "Brak daty zakończenia",
    "endAfterCaption": "Koniec po",
    "endDateCaption": "Zakończ do",
    "saveButtonCaption": "Zapisz",
    "optionsButtonCaption": "Opcje",
    "cancelButtonCaption": "Anuluj",
    "recurrenceButtonCaption": "Powtarzalność",
    "deleteButtonCaption": "Usuń",
    "secondsValue": "sekundy",
    "minuteValue": "minuta",
    "minutesValue": "minuty",
    "hourValue": "godzina",
    "hoursValue": "godziny",
    "dayValue": "dzień",
    "daysValue": "dni",
    "weeksValue": "tygodnie",
    "monthValue": "miesiąc",
    "dailyValue": "codziennie",
    "weeklyValue": "tygodniowo",
    "monthlyValue": "miesięcznie",
    "yearlyValue": "rocznie",
    "intervalValue": "Według przedziału czasowego",
    "firstValue": "pierwszy",
    "secondValue": "drugi",
    "thirdValue": "trzeci",
    "fourthValue": "czwarty",
    "lastValue": "ostatni",
    "weekendValue": "weekend",
    "weekdayValue": "dzień roboczy",
    "recurrenceDailyOnePattern": "Występuje każdego dnia",
    "recurrenceDailyTwoPattern": "Występuje co [Days] dni",
    "recurrenceDailyThreePattern": "Występuje w każdym dniu roboczym",
    "recurrenceDailyFourPattern": "Występuje w każdy dzień weekendu",
    "recurrenceWeeklyOnePattern": "Występuje w każdy [DaysOfWeek]",
    "recurrenceWeeklyTwoPattern": "Występuje każdego [Weeks] tygodnia w [DaysOfWeek]",
    "recurrenceMonthlyOnePattern": "Występuje [DayOfMonth] każdego [Months] miesiąca",
    "recurrenceMonthlyTwoPattern": "Występuje [Occurrence] [Day] każdego [Months] miesiąca",
    "recurrenceYearlyOnePattern": "Występuje każdego [MonthOfYear] [DayOfMonth]",
    "recurrenceYearlyTwoPattern": "Występuje [Occurrence] [Day] [MonthOfYear]",
    "recurrenceIntervalPattern": "Występuje każdego [Interval.Days] dni [Interval.Hours] godziny [Interval.Minutes] minuty [Interval.Seconds] sekundy",
    "recurrenceStartDatePattern": "skuteczne [StartDate]",
    "recurrenceEndDatePattern": "do[EndDate]",
    "recurrenceTimeOnePattern": "z [StartTime] do [EndTime]",
    "recurrenceTimeTwoPattern": "o [StartTime]",
    "taskFormHeader": "Zadanie",
    "taskPriorityLow": "Niski",
    "taskPriorityNormal": "Normalny",
    "taskPriorityHigh": "Wysoki",
    "taskStatusNotStarted": "Not rozpoczęte",
    "taskStatusInProgress": "W realizacji",
    "taskStatusCompleted": "Ukończone",
    "taskStatusWaiting": "Oczekuje na kogoś innego",
    "taskStatusDeferred": "Odroczone",
    "percentCompleteCaption": "% Ukończone",
    "dueDateCaption": "Data ukończenia",
    "priorityCaption": "Priorytet",
    "startDateCaption": "Data rozpoczęcia",
    "statusCaption": "Status",
    "timeCaption": "Czas",
    "oKButtonCaption": "OK",
    "removeButtonCaption": "Usuń",
    "weekValue": "tydzień",
    "durationCaption": "Czas trwania",
    "endCaption": "Koniec",
    "daysCaption": "Dni",
    "hoursCaption": "Godziny",
    "minutesCaption": "Minuty",
    "secondsCaption": "Sekundy",
    "monthsValue": "miesiąc(e)",
    "recurEveryValue": "Pojawia się każdego",
    "occurrencesValue": "Występowanie",
    "weeksOnValue": "week(s) tygodnia(i) w",
    "everyWeekdayValue": "Każdgo dnia roboczego",
    "everyWeekendValue": "Każdego dnia w weekend",
    "theValue": "-",
    "invalidRecurrenceIntervalHeader": "Nieprawidłowa rekurencja",
    "invalidRecurrenceIntervalMessage": "Odstęp między powtórzeniami musi być większy niż zero.",
    "confirmRecurrenceRemoveHeader": "Usuń rekurencję",
    "confirmRecurrenceRemoveMessage": "Potwierdzić usunięcie rekurencji?"
  }
};