export const locale = {
  "locale": "tr-TR",
  "strings": {
      "newFormHeader": "Randevu",
      "editFormHeader": "Randevuyu Düzenle",
      "newRecurrenceFormHeader": "Tekrarlama",
      "editRecurrenceFormHeader": "Tekrarlamayı Düzenle",
      "cueFormHeader": "İşaret Öğeleri",
      "dateCaption": "Tarih",
      "datesCaption": "Tarihler",
      "subjectCaption": "Konu",
      "startTimeCaption": "Başlama Zamanı",
      "endTimeCaption": "Bitiş Zamanı",
      "allDayEventCaption": "Tüm gün süren aktivite",
      "reminderCaption": "Hatırlatıcı",
      "detailsCaption": "Detaylar",
      "contactsCaption": "Rehber",
      "todayCaption": "Bugün",
      "locationCaption": "Konum",
      "patternCaption": "Dağılım",
      "rangeCaption": "Tekrarlama Aralığı",
      "everyCaption": "Hepsi",
      "ofEveryCaption": "’nin Hepsi",
      "startCaption": "Başla",
      "noEndCaption": "Bitiş Tarihi Yok",
      "endAfterCaption": "Şundan Sonra Bitir",
      "endDateCaption": "Şu Tarihte Bitir",
      "saveButtonCaption": "Kaydet",
      "optionsButtonCaption": "Ayarlar",
      "cancelButtonCaption": "İptal Et",
      "recurrenceButtonCaption": "Tekrarlama",
      "deleteButtonCaption": "Sil",
      "secondsValue": "Saniye",
      "minuteValue": "Dakika",
      "minutesValue": "Saniyeler",
      "hourValue": "Saat",
      "hoursValue": "Saatler",
      "dayValue": "Gün",
      "daysValue": "Günler",
      "weeksValue": "Haftalar",
      "monthValue": "Ay",
      "dailyValue": "Günlük",
      "weeklyValue": "Haftalık",
      "monthlyValue": "Aylık",
      "yearlyValue": "Yıllık",
      "intervalValue": "Zaman aralığına göre",
      "firstValue": "ilk",
      "secondValue": "ikinci",
      "thirdValue": "üçüncü",
      "fourthValue": "dördüncü",
      "lastValue": "son",
      "weekendValue": "hafta sonu",
      "weekdayValue": "hafta içi",
      "recurrenceDailyOnePattern": "Her Gün Yapılıyor",
      "recurrenceDailyTwoPattern": "Her [Days] Günü Yapılıyor",
      "recurrenceDailyThreePattern": "Her Hafta içi Yapılıyor",
      "recurrenceDailyFourPattern": "Her Hafta sonu Yapılıyor",
      "recurrenceWeeklyOnePattern": "Her [DaysOfWeek] tekrar ediyor",
      "recurrenceWeeklyTwoPattern": "Her [Weeks] haftada [DaysOfWeek] günü tekrar ediyor",
      "recurrenceMonthlyOnePattern": "Her [DayOfMonth] günü [Months]ay(lar)ında oluyor",
      "recurrenceMonthlyTwoPattern": "Her [Months] ay(lar)ı [Occurrence] [Day]günü oluyor",
      "recurrenceYearlyOnePattern": "Her [MonthOfYear] [DayOfMonth] oluyor",
      "recurrenceYearlyTwoPattern": "[MonthOfYear] ayında [Occurrence] [Day] günü oluyor",
      "recurrenceIntervalPattern": "Her [Interval.Days] günü saat[Interval.Hours] dakika [Interval.Minutes] saniye [Interval.Seconds] olduğunda tekrarlanıyor",
      "recurrenceStartDatePattern": "etkin [StartDate]",
      "recurrenceEndDatePattern": "[EndDate] a kadar",
      "recurrenceTimeOnePattern": "[StartTime] dan [EndTime] a kadar",
      "recurrenceTimeTwoPattern": "[StartTime] da",
      "taskFormHeader": "Görev",
      "taskPriorityLow": "Düşük",
      "taskPriorityNormal": "Normal",
      "taskPriorityHigh": "Yüksek",
      "taskStatusNotStarted": "Başlamadı",
      "taskStatusInProgress": "Devam Etmekte",
      "taskStatusCompleted": "Tamamlandı",
      "taskStatusWaiting": "Başka birisi bekleniyor",
      "taskStatusDeferred": "Ertelendi",
      "percentCompleteCaption": "% Tamamlandı",
      "dueDateCaption": "Bitiş Tarihi",
      "priorityCaption": "Öncelik",
      "startDateCaption": "Başlama Tarihi",
      "statusCaption": "Durum",
      "timeCaption": "Zaman",
      "oKButtonCaption": "Tamam",
      "removeButtonCaption": "Kaldır",
      "weekValue": "hafta",
      "durationCaption": "Süre",
      "endCaption": "Bitir",
      "daysCaption": "Gün",
      "hoursCaption": "Saat",
      "minutesCaption": "Dakika",
      "secondsCaption": "Saniye",
      "monthsValue": "Ay(lar)",
      "recurEveryValue": "şu durumda tekrarla",
      "occurrencesValue": "olaylar",
      "weeksOnValue": "hafta(lar)",
      "everyWeekdayValue": "Her Hafta içi",
      "everyWeekendValue": "Her Hafta sonu",
      "theValue": "",
      "invalidRecurrenceIntervalHeader": "Geçersiz Tekrarlama",
      "invalidRecurrenceIntervalMessage": "Tekrarlama sıklığı sıfırdan büyük olmalıdır.",
      "confirmRecurrenceRemoveHeader": "Tekrarlamayı Kaldır",
      "confirmRecurrenceRemoveMessage": "Tekrarlamanın Kaldırılmasını Onaylıyor musunuz?"
    }
  };